### ISSUE TITLE
Error in schema validation for ToleratedFailureCount

### ISSUE THREAD

**Issue by ayansen979** [ChristopheBougere/asl-validator#121]
Describe the bug
Error when try to deploy from serverless yaml as JSON path with **"ToleratedFailureCountPath"** or any of these with validate mode ON.
**

**ToleratedFailureCountPath/ToleratedFailureCount
ToleratedFailurePercentagePath/ToleratedFailurePercentageCount**

**
Error: 
✕ State machine "myMachine" definition is invalid:
SCHEMA_VALIDATION_FAILED: /States/X is invalid. must match exactly one schema in oneOf
To Reproduce
Please provide a complete state machine definition:

```
    maMachine:
      name: 'maMachine'
      definition:
        Comment: 'step f demo distributed mode'
        StartAt: X
        States:
          X:
            Type: Map
            MaxConcurrency: 100
            ToleratedFailureCountPath: "$.Count"
            ItemsPath: "$"
            ItemReader:
              ReaderConfig:
                InputType: JSON
              Resource: 'arn:aws:states:::s3:getObject'
              Parameters:
                Bucket: 'BUCKET_NAME'
                Key: 'key'
            ItemProcessor:
              ProcessorConfig:
                Mode: DISTRIBUTED
                ExecutionType: EXPRESS
              StartAt: ProcessArrayElement
              States:
                ProcessArrayElement:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [lambdafunc, Arn]
                  End: true
            Label: Map
            End: true
```

Expected behavior
State machine "myMachine" definition is valid

Version:
node 16.17.0
serverless 3.25.1
SDK 4.3.2
serverless-step-functions: "^3.12.0"
