### ISSUE TITLE
Validation failed on field using States.MathAdd functions

### ISSUE THREAD

**Issue by OranShuster** [ChristopheBougere/asl-validator#165]
**Describe the bug**
asl-validator returns a SCHEMA_VALIDATION_FAILED error when it is not expected.

$ npx asl-validator --yaml-path test.asl.json
✕ State machine definition "test.asl.json" is invalid:
 SCHEMA_VALIDATION_FAILED: /States/Get Record Outputs/Parameters/FooBar.$ is invalid. must match format "asl_payload_template"

**To Reproduce**
Step function definition:

```yaml
Comment: A description of my state machine
StartAt: validate input
States:
  validate input:
    Type: Pass
    Parameters:
      foo.$: "States.MathAdd(States.ArrayLength($$.Execution.Input.machines),-1)"
    ResultPath: "$.input"
    End: true
```

**Expected behavior**
Should not return an error

**Version:**
3.10.0

**Additional context**
None
