### ISSUE TITLE
Incorrect transition target error for Choice state

### ISSUE THREAD

**Issue by vbhavsar** [ChristopheBougere/asl-validator#64]
For a Choice state, Default target is optional [1]. Yet asl-validator fails when Default is not present.

For example, this
```yaml
Choose X:
  Type: Choice
  Choices:
    - Variable: "$.foo"
      BooleanEquals: true
      Next: True State
    - Variable: "$.foo"
      BooleanEquals: false
      Next: False State
```

will fail with
```json
[
  {
    'Error code': 'MISSING_TRANSITION_TARGET',
    Message: "Missing 'StartAt'|'Next'|'Default' target: Choose X"
  }
]
```

I believe this condition needs to be fixed
https://github.com/ChristopheBougere/asl-validator/blob/45a803935f4a61f741036f13149dcd9dc161c124/src/lib/missing-transition-target.js#L23-L28

[1] https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html
