### ISSUE TITLE
Pass state fails validation when InputPath is used to access the Context Object

### ISSUE THREAD

**Issue by dalecampbell** [ChristopheBougere/asl-validator#65]
Hello, In August 2020, AWS [released](https://aws.amazon.com/blogs/aws/aws-step-functions-adds-updates-to-choice-state-global-access-to-context-object-dynamic-timeouts-result-selection-and-intrinsic-functions-to-amazon-states-languages/) numerous updates for Step Functions, most of which you support. They added support for accessing the Context Object outside of just Parameters. See https://docs.aws.amazon.com/step-functions/latest/dg/input-output-contextobject.html

When using a Pass State with an InputPath to referencing the $$.Execution.Id the validator returns an error even though this properly deployed and works without issue. I also started an [issue](https://github.com/serverless-operations/serverless-step-functions/issues/402) at serverless-step-functions, but it seems the correct place for this is here. I have tested this InputPath in other states and it seems the same issue exists across the board. 
 
```
definition:
  Comment: "Testing getting Context Object from InputPath in Pass State"
  StartAt: pass-execution-details
  States:
    pass-execution-details:
      Type: Pass
      ResultPath: $.AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID
      InputPath: $$.Execution.Id
      End: True
```

This fails with:

```
✕ State machine "test-pass-inputpath" definition is invalid:
  undefined: undefined
  No errors
```

The code from [serverless-step-functions](https://github.com/serverless-operations/serverless-step-functions)

```
        if (stateMachineObj.definition) {
          if (this.serverless.service.stepFunctions.validate) {
            const { isValid, errorsText } = aslValidator(stateMachineObj.definition);
            if (isValid) {
              this.serverless.cli.consoleLog(`✓ State machine "${stateMachineName}" definition is valid`);
            } else {
              const errorMessage = [
                `✕ State machine "${stateMachineName}" definition is invalid:`,
                errorsText(),
              ].join('\n');
              throw new this.serverless.classes.Error(errorMessage);
            }
          }
```

**Comment by ChristopheBougere** [comment]
Thanks for the detailed bug report @dalecampbell 
I believe #66 should fix it
Could you give a try to v1.9.4 and let me know?

**Comment by dalecampbell** [comment]
Updated and tested with the same error. 

```
npm list -g asl-validator
/usr/local/lib
├── asl-validator@1.9.4 
└─┬ serverless-step-functions@2.29.0
  └── asl-validator@1.9.4 
```

```
  Serverless Error ---------------------------------------
 
  ✕ State machine "episodeIngest" definition is invalid:
  undefined: undefined
  No errors
```

**Comment by ChristopheBougere** [comment]
Could you provide your entire serverless.yml file then?
When I try with this one it passes on my side:
```yaml
service: test
provider:
  name: aws
plugins:
  - serverless-step-functions
stepFunctions:
  validate: true
  stateMachines:
    hellostepfunc1:
      definition:
        Comment: "Testing getting Context Object from InputPath in Pass State"
        StartAt: pass-execution-details
        States:
          pass-execution-details:
            Type: Pass
            ResultPath: $.AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID
            InputPath: $$.Execution.Id
            End: True
```

**Comment by dalecampbell** [comment]
Here is my trimmed down serverless.yml  which shows the failure when I attempt to deploy. 

```
service: test-pass-inputpath

provider:
  name: aws
  runtime: python3.8
  stage: dev
  profile: msc_dev

plugins:
  - serverless-step-functions

stepFunctions:
  validate: true
  stateMachines:
    test-pass-inputpath:
      name: test-pass-inputpath
      definition:
        Comment: "Testing getting Context Object from InputPath in Pass State"
        StartAt: pass-execution-details
        States:
          pass-execution-details:
            Type: Pass
            ResultPath: $.AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID
            InputPath: $$.Execution.Id
            End: True

```
